name: PR Comment

inputs:
  comment:
    type: string
    required: true

  error:
    type: string
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      env:
        COMMENT: ${{ inputs.comment }}
        ERROR: ${{ inputs.error || inputs.comment }}
      with:
        script: |
          const comment = process.env.COMMENT
          const error = process.env.ERROR
          github.rest.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: comment
          })

          core.setFailed(error)
