name: testing
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test:
    name: create matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        option:
          - dev
          - prod

  dosomething:
    name: something prod env
    runs-on: ubuntu-latest
    environment: ${{ matrix.option }}
    steps:
      - name: Something
        run: echo "Hello, running in env ${{ matrix.option }}"
