name: testing
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/action
      - name: ls
        run: ls -la $GITHUB_WORKSPACE/
      - uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: .
