name: testing
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write



jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: echo OK

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        option:
          - dev
          - prod

    environment: ${{ matrix.option }}

    steps:
      - name: Something
        run: echo "Hello, running in env ${{ matrix.option }}"

      - name: Something else
        run: echo change
