name: testing
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/action
      - uses: actions/upload-artefact@v3
        with:
          name: test-file
          path: ${{ env.RUNNER_TEMP }}/testing
