name: testing
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - name: fail
        id: fail
        uses: actions/github-script@v7
        with:
          script: core.setFailed('fail')
        continue-on-error: true

      - name: report failure
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && steps.fail.outcome == 'failure'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Terraform formatting issues were found. Please run `terraform fmt -recursive` locally and commit the changes.'
            })
            core.setFailed('Terraform formatting issues')
