name: testing
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - name: fail
        id: fail
        uses: actions/github-script@v7
        with:
          script: core.setFailed('fail')
        continue-on-error: true

      - name: report failure
        if: github.event_name == 'pull_request' && steps.fail.outcome == 'failure'
        uses: ./.github/workflows/pr-comment.yml
        with:
          comment: '⚠️ Terraform formatting issues were found. Please run `terraform fmt -recursive` locally and commit the changes.'
