name: testing
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write



jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: format
        run: echo format

  auth-check:
    name: Auth check
    runs-on: ubuntu-latest
    steps:
      - name: Auth check
        run: echo auth check

  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: [fmt, auth-check]
    strategy:
      matrix:
        option:
          - dev
          - prod
    steps:
      - name: Plan
        run: echo plan ${{ matrix.option }}

  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: [plan]
    strategy:
      matrix:
        option:
          - dev
          - prod
    environment: ${{ matrix.option }}
    steps:
      - name: Apply
        run: echo apply ${{ matrix.option }}
